### ISSUE TITLE
Having an issue with mysql inside of clustercontrol image

### ISSUE THREAD

**Issue by thomascooper** [severalnines/docker#18] opened 2018-01-02 18:41 UTC
I followed the guide here:
https://severalnines.com/blog/mysql-docker-running-galera-cluster-production-clustercontrol-kubernetes

The only real changes are that my volumes are using my glusterfs rather than NFS, my cc-rs.yml is here: https://gist.github.com/thomascooper/77eb857abaa9433fa2c889031a38c824

This creates the cc pod, but it fails on starting mysql, I can see that the expected files are created in the volume:
-rw-rw---- 1 999 997       56 Jan  2 07:55 auto.cnf
-rw-rw---- 1 999 997   105250 Jan  2 08:31 error.log
-rw-rw---- 1 999 997 50331648 Jan  2 08:31 ib_logfile0
-rw-rw---- 1 999 997 50331648 Jan  2 07:55 ib_logfile1
-rw-rw---- 1 999 997 12582912 Jan  2 07:55 ibdata1

But  mysql continually dies and so does the container, here is the container log and error.log:
>> Datadir is not empty..
>> Ensure MySQL datadir has correct permission/ownership..
 >> Starting MySQL daemon..
180102 18:27:15 mysqld_safe Logging to '/var/lib/mysql/error.log'.
180102 18:27:15 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
180102 18:27:16 mysqld_safe mysqld from pid file /var/lib/mysql/mysqld.pid ended
 >> MySQL failed to start. Aborting..

error.log: https://gist.github.com/thomascooper/307d39fae8fcf7447a55551dbb1a9181

To test this further I replaced the datadir with a GCEPersistent disk claim, same exact issue. I have also tried using clustercontrol:1.4.2 (which i assume was the version used during the walkthrough), and it had the exact same result.

Any help would be greatly appreciated

**Comment by ashraf-s9s** [comment] 2018-01-09 23:09
Hi @thomascooper ,

It looks like the MySQL data directory was already existed and didn't contain mysql.user table. Can you make sure that the PV is new and fresh so the image can initialize the datadir content? If the datadir is not empty, the entrypoint script will skip MySQL initialization and just proceed with correcting permissions/ownership and starting up the MySQL.

**Comment by thomascooper** [comment] 2018-01-09 23:23
@ashraf-s9s 

The both drives, the GCE and Gluster were both empty at the time of initialization, aside from whatever hidden files are created on them (like .trashcan on gluster). In both cases I actually logged the disk on another machine and executed a 'rm -rf *` in the root directory, as well as deleting the disks and recreating them as part of the play that starts cluster control.

**Comment by cpjolly** [comment] 2018-07-21 16:06
@ashraf-s9s,

I am having similar issues using this image with PVCs on Google Cloud. I am using the Kubernetes Deployment example cc-rs.yml.

I think the issue is the test on line 41 of entrypoint.sh where it checks if the DATADIR  /var/lib/mysql is empty using the following test.

`if [ "$(ls -A $DATADIR)" ]; then`

This is fine for non-root folder mounts, like your NFS examples from your blog post of last year, but in this case the root folder of a PVC volume (called mysql-datadir in cc-rs.yml) is mounted directly on /var/lib/mysql.

The root folder of a standard PVC generated by Google Cloud will contain a lost+found folder, so it's not empty and this test will always fail, so the DATADIR is never initialised and the container exists with an error.

**Comment by ashraf-s9s** [comment] 2018-07-24 08:03
I've added check inside entrypoint script to ignore "lost+found" directory during MySQL initialization. Closing this issue.

**Closed by ashraf-s9s** 2018-07-24 08:03 UTC

**Comment by cpjolly** [comment] 2018-07-24 10:38
Thanks @ashraf-s9s ,

I have tested the updated image and it work perfectly in my StatefulSet on Google Kubernetes with auto-generated PVCs. Nice catch with adding the "ignore-db-dir=lost+found" to my.cnf. I forgot to mention that...

Many thanks
